# Generated by Django 5.0.3 on 2026-05-25 23:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='current quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='reserved quantity')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=5, help_text='Alert when stock falls below this level', max_digits=10, verbose_name='minimum stock')),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock limit (optional)', max_digits=10, null=True, verbose_name='maximum stock')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=10, help_text='Stock level that triggers reorder', max_digits=10, verbose_name='reorder point')),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=20, help_text='Quantity to reorder when stock reaches reorder point', max_digits=10, verbose_name='reorder quantity')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='out_of_stock', max_length=20, verbose_name='stock status')),
                ('warehouse_location', models.CharField(blank=True, max_length=200, verbose_name='warehouse location')),
                ('shelf_number', models.CharField(blank=True, max_length=50, verbose_name='shelf number')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=100, verbose_name='order ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='status')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'inventory reservation',
                'verbose_name_plural': 'inventory reservations',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiring', 'Expiring Soon')], max_length=20, verbose_name='alert type')),
                ('message', models.TextField(verbose_name='alert message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('resolved', 'Resolved')], default='pending', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'stock alert',
                'verbose_name_plural': 'stock alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damage'), ('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('release', 'Release')], max_length=20, verbose_name='movement type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='previous quantity')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='new quantity')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('reference_id', models.CharField(blank=True, help_text='Order ID, etc.', max_length=100, verbose_name='reference ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'status'], name='inventory_i_product_4b2c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity', 'minimum_stock'], name='inventory_i_quantit_7f6e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['order_id', 'status'], name='inventory_i_order_i_283ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['expires_at'], name='inventory_i_expires_858ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory', '-created_at'], name='inventory_s_invento_c5d628_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
    ]
