"""
Django settings for Wakulima project.
Generated by 'django-admin startproject' using Django 5.0.3.
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ========== Security ==========
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in .env file")

DEBUG = os.getenv("DEBUG", "False") == "True"

# ========== ALLOWED_HOSTS Configuration ==========
allowed_hosts_raw = os.getenv("ALLOWED_HOSTS")
if not allowed_hosts_raw:
    raise ValueError("ALLOWED_HOSTS must be set in .env file")
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(",")]

# Add development domains if DEBUG is True
if DEBUG:
    dev_domains_raw = os.getenv("DEV_ALLOWED_HOSTS")
    if dev_domains_raw:
        dev_domains = [domain.strip() for domain in dev_domains_raw.split(",")]
        ALLOWED_HOSTS.extend(dev_domains)
        ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# ========== Application definition ==========
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_cleanup.apps.CleanupConfig",
    # Local apps
    "apps.accounts.apps.AccountsConfig",
    "apps.products.apps.ProductsConfig",
    "apps.cart.apps.CartConfig",
    "apps.orders.apps.OrdersConfig",
    "apps.payments.apps.PaymentsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.inventory.apps.InventoryConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ========== Database Configuration ==========
DATABASE_ENGINE = os.getenv("DATABASE_ENGINE")
if not DATABASE_ENGINE:
    raise ValueError("DATABASE_ENGINE must be set in .env file")

DATABASE_NAME = os.getenv("DATABASE_NAME")
if not DATABASE_NAME:
    raise ValueError("DATABASE_NAME must be set in .env file")

if DATABASE_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": BASE_DIR / DATABASE_NAME,
        }
    }
else:
    DATABASE_USER = os.getenv("DATABASE_USER")
    DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
    DATABASE_HOST = os.getenv("DATABASE_HOST")
    DATABASE_PORT = os.getenv("DATABASE_PORT")

    if not all(
        [DATABASE_USER, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT]
    ):
        raise ValueError(
            "PostgreSQL requires DATABASE_USER, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT in .env"
        )

    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": DATABASE_NAME,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
        }
    }

# ========== Custom user model ==========
AUTH_USER_MODEL = "accounts.User"

# ========== Password validation ==========
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ========== Internationalization ==========
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("TIME_ZONE", "Africa/Nairobi")
USE_I18N = True
USE_TZ = True

# ========== Static files (CSS, JavaScript, Images) ==========
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "static/media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========== REST Framework settings ==========
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.getenv("PAGE_SIZE", 20)),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ========== Throttling (Enabled only in production) ==========
ENABLE_THROTTLING = os.getenv("ENABLE_THROTTLING", "False") == "True"

if ENABLE_THROTTLING:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": os.getenv("THROTTLE_ANON", "100/day"),
        "user": os.getenv("THROTTLE_USER", "1000/day"),
        "register": os.getenv("THROTTLE_REGISTER", "5/hour"),
        "password_reset": os.getenv("THROTTLE_PASSWORD_RESET", "3/hour"),
    }

# ========== Spectacular (Swagger/OpenAPI) Configuration ==========
SPECTACULAR_SETTINGS = {
    "TITLE": "Wakulima API",
    "DESCRIPTION": """
# 🌾 Wakulima E-commerce Platform API

Wakulima connects farmers directly to consumers, enabling seamless buying and selling of agricultural products.

## 🔐 Authentication
This API uses JWT (JSON Web Token) authentication.

### How to authenticate:
1. **Register** a user: `POST /api/v1/auth/register/`
2. **Login** at: `POST /api/v1/auth/login/` to get your access token
3. **Authorize** your requests by entering: `Bearer your_access_token`

## 👥 User Roles & Permissions

| Role | Permissions |
|------|-------------|
| **Customer** (Default) | Browse products, add to cart, place orders, write reviews |
| **Farmer** (Requires upgrade) | Create/manage products, update inventory, view orders |
| **Admin** | Full access to all resources, manage categories, approve reviews |

## 📊 Rate Limits

| Endpoint Type | Limit |
|---------------|-------|
| Anonymous | 100 requests/day |
| Authenticated | 1000 requests/day |
| Registration | 5 requests/hour |
| Password Reset | 3 requests/hour |

## 📚 API Modules

### 🔑 Authentication (`/auth/`)
- User registration, login, logout
- Profile management
- Password reset (OTP-based)
- Email verification
- Farmer upgrade requests

### 📦 Products (`/products/`)
- Product CRUD operations
- Category management
- Product reviews
- Image upload (multipart)
- Filtering & search

### 🛒 Cart (`/cart/`)
- Add/remove items
- Update quantities
- Cart summary for checkout

### 📋 Orders (`/orders/`)
- Create orders from cart
- Order tracking
- Cancel orders
- Order history

### 💳 Payments (`/payments/`)
- M-Pesa STK Push
- PayPal integration
- Payment status queries
- Refunds (PayPal)

### 📦 Inventory (`/inventory/`)
- Stock management
- Stock movement history
- Low stock alerts
- Bulk stock updates

### 🔔 Notifications (`/notifications/`)
- In-app notifications
- Mark as read/unread
- Email/SMS test endpoints

## ❌ Error Responses

| Code | Meaning |
|------|---------|
| 200 | Success |
| 201 | Created |
| 400 | Bad Request - Validation error |
| 401 | Unauthorized - Invalid/missing token |
| 403 | Forbidden - Insufficient permissions |
| 404 | Not Found |
| 429 | Too Many Requests - Rate limit exceeded |
| 500 | Internal Server Error |

## 🧪 Testing Credentials

### Test User (Customer)
- Email: `jerrynabango9@gmail.com`
- Password: `Test@123456`

### Admin User
- Email: `jnabango@gmail.com`
- Password: `Admin@123456`

### M-Pesa Sandbox
- Phone: `254708374149`
- PIN: `123456`

## 🔗 Useful Links

- [ReDoc Documentation](/redoc/)
- [Admin Panel](/admin/)
- [GitHub Repository](https://github.com/yourusername/wakulima-api)

---
*Built with Django REST Framework | © 2026 Wakulima*
""",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    # FIX: Use sidecar for local asset serving - Fixes ReDoc blank page issue
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
        "docExpansion": "none",
        "defaultModelsExpandDepth": -1,
    },
    "ENABLE_DOCS": True,
}

# ========== Content Security Policy (Optional but recommended) ==========
# Only enable these if you need custom CSP headers
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
# CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")
# CSP_IMG_SRC = ("'self'", "data:", "https:")

# ========== JWT Settings ==========
JWT_ACCESS_LIFETIME = int(os.getenv("JWT_ACCESS_LIFETIME", 60))
JWT_REFRESH_LIFETIME = int(os.getenv("JWT_REFRESH_LIFETIME", 7))

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=JWT_ACCESS_LIFETIME),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=JWT_REFRESH_LIFETIME),
    "ROTATE_REFRESH_TOKENS": os.getenv("JWT_ROTATE_REFRESH_TOKENS", "True")
    == "True",
    "BLACKLIST_AFTER_ROTATION": os.getenv(
        "JWT_BLACKLIST_AFTER_ROTATION", "True"
    )
    == "True",
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# ========== CORS Configuration ==========
cors_origins_raw = os.getenv("CORS_ALLOWED_ORIGINS")
if not cors_origins_raw:
    raise ValueError("CORS_ALLOWED_ORIGINS must be set in .env file")
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in cors_origins_raw.split(",")
]

if DEBUG:
    dev_cors_origins_raw = os.getenv("DEV_CORS_ALLOWED_ORIGINS")
    if dev_cors_origins_raw:
        dev_cors_origins = [
            origin.strip() for origin in dev_cors_origins_raw.split(",")
        ]
        CORS_ALLOWED_ORIGINS.extend(dev_cors_origins)

CORS_ALLOW_CREDENTIALS = True

# ========== Email settings ==========
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

if not all(
    [
        EMAIL_BACKEND,
        EMAIL_HOST,
        EMAIL_HOST_USER,
        EMAIL_HOST_PASSWORD,
        DEFAULT_FROM_EMAIL,
    ]
):
    import warnings

    warnings.warn("Email settings incomplete. Email sending will fail.")

# ========== Frontend URL ==========
FRONTEND_URL = os.getenv("FRONTEND_URL")
if not FRONTEND_URL:
    raise ValueError("FRONTEND_URL must be set in .env file")

# ========== Redis / Celery Configuration ==========
REDIS_URL = os.getenv("REDIS_URL")
if not REDIS_URL:
    raise ValueError("REDIS_URL must be set in .env file")

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    "check-pending-payments": {
        "task": "apps.payments.tasks.check_pending_payments",
        "schedule": int(os.getenv("CELERY_BEAT_PAYMENTS_INTERVAL", 300)),
    },
    "check-low-stock": {
        "task": "apps.inventory.tasks.check_all_low_stock",
        "schedule": int(os.getenv("CELERY_BEAT_STOCK_INTERVAL", 3600)),
    },
    "expire-reservations": {
        "task": "apps.inventory.tasks.expire_old_reservations",
        "schedule": int(os.getenv("CELERY_BEAT_RESERVATIONS_INTERVAL", 600)),
    },
}

# ========== Cache settings ==========
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# ========== PayPal Configuration ==========
PAYPAL_MODE = os.getenv("PAYPAL_MODE", "sandbox")
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")
PAYPAL_WEBHOOK_ID = os.getenv("PAYPAL_WEBHOOK_ID")

# ========== M-Pesa Configuration ==========
MPESA_ENVIRONMENT = os.getenv("MPESA_ENVIRONMENT", "sandbox")
MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE", "174379")
MPESA_CALLBACK_URL = os.getenv("MPESA_CALLBACK_URL")
MPESA_IP_WHITELIST_ENABLED = (
    os.getenv("MPESA_IP_WHITELIST_ENABLED", "True") == "True"
)

# M-Pesa IP Whitelist
mpesa_ip_whitelist_raw = os.getenv("MPESA_IP_WHITELIST", "")
if mpesa_ip_whitelist_raw:
    MPESA_IP_WHITELIST = [
        ip.strip() for ip in mpesa_ip_whitelist_raw.split(",")
    ]
else:
    MPESA_IP_WHITELIST = []

# ========== SendGrid Configuration ==========
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
EMAIL_FROM_NAME = os.getenv("EMAIL_FROM_NAME", "Wakulima")

# ========== Africa's Talking Configuration ==========
AFRICASTALKING_USERNAME = os.getenv("AFRICASTALKING_USERNAME")
AFRICASTALKING_API_KEY = os.getenv("AFRICASTALKING_API_KEY")
AFRICASTALKING_SANDBOX = os.getenv("AFRICASTALKING_SANDBOX", "True") == "True"
AFRICASTALKING_SENDER_ID = os.getenv("AFRICASTALKING_SENDER_ID")

# ========== Support Contact ==========
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL")
SUPPORT_PHONE = os.getenv("SUPPORT_PHONE")

# ========== Logging ==========
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "apps.accounts": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
