# Generated by Django 5.0.3 on 2026-05-25 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254, verbose_name='to email')),
                ('from_email', models.EmailField(default='your-personal-email@gmail.com', max_length=254, verbose_name='from email')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('low_stock', 'Low Stock Alert'), ('farmer_welcome', 'Farmer Welcome'), ('refund_processed', 'Refund Processed')], max_length=50, verbose_name='template type')),
                ('html_content', models.TextField(verbose_name='HTML content')),
                ('plain_text_content', models.TextField(blank=True, verbose_name='plain text content')),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=100, verbose_name='SendGrid message ID')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='reference ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_phone', models.CharField(max_length=15, verbose_name='to phone')),
                ('from_phone', models.CharField(blank=True, max_length=15, verbose_name='from phone')),
                ('message', models.TextField(verbose_name='message')),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('otp_verification', 'OTP Verification'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert')], max_length=50, verbose_name='template type')),
                ('message_id', models.CharField(blank=True, max_length=100, verbose_name='message ID')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='status')),
                ('status_code', models.CharField(blank=True, max_length=10, verbose_name='status code')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='cost')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='reference ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
            ],
            options={
                'verbose_name': 'SMS log',
                'verbose_name_plural': 'SMS logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20, verbose_name='type')),
                ('category', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('auth', 'Authentication'), ('promotion', 'Promotion'), ('alert', 'Alert'), ('system', 'System')], max_length=20, verbose_name='category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML content')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered', models.BooleanField(default=False, verbose_name='delivered')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='retry count')),
                ('template_type', models.CharField(blank=True, max_length=50, verbose_name='template type')),
                ('reference_id', models.CharField(blank=True, help_text='Order ID, Payment ID, etc.', max_length=100, verbose_name='reference ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['sent', 'created_at'], name='notificatio_sent_354551_idx'), models.Index(fields=['notification_type', 'category'], name='notificatio_notific_bf99e0_idx')],
            },
        ),
    ]
