# Generated by Django 5.0.3 on 2026-06-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='from_email',
            field=models.EmailField(default='jnabango@gmail.com', max_length=254, verbose_name='from email'),
        ),
    ]
